name: mmpose
channels:
  - defaults
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1

  - pip:
      - addict==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2026.1.4
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - chumpy==0.70
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - coverage==7.6.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.4
      - eval-type-backport==0.3.1
      - exceptiongroup==1.3.1
      - filelock==3.14.0
      - flake8==7.1.2
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - interrogate==1.7.0
      - isort==4.3.21
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmdet==3.2.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - munkres==1.1.4
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.13.0.90
      - opencv-python-headless==4.13.0.90
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - parameterized==0.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - py==1.11.0
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyflakes==3.2.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pytest==8.3.5
      - pytest-runner==6.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - requests==2.28.2
      - rich==13.4.2
      - scikit-image==0.21.0
      - scipy==1.10.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tifffile==2023.7.10
      - tomli==2.4.0
      - tqdm==4.65.2
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==1.26.20
      - xdoctest==1.3.0
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - zipp==3.20.2
